# Generated by Django 6.0.2 on 2026-02-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-updated',)},
        ),
    ]
